// List of enums

// Action IDs are used in interactive blocks
export enum SlackActionId {
  CLOSED_VOTER_PANEL_UNDO_BUTTON = 'CLOSED_VOTER_PANEL_UNDO_BUTTON',
  VOLUNTEER_DROPDOWN = 'VOLUNTEER_DROPDOWN',
  VOTER_STATUS_DROPDOWN = 'VOTER_STATUS_DROPDOWN',
  VOTER_STATUS_VOTED_BUTTON = 'VOTER_STATUS_VOTED_BUTTON',
  VOTER_STATUS_REFUSED_BUTTON = 'VOTER_STATUS_REFUSED_BUTTON',
  VOTER_STATUS_SPAM_BUTTON = 'VOTER_STATUS_SPAM_BUTTON',
}
