// List of enums

// Action IDs are used in interactive blocks
export enum SlackActionId {
  CLOSED_VOTER_PANEL_UNDO = 'CLOSED_VOTER_PANEL_UNDO',
  VOLUNTEER_UPDATE = 'VOLUNTEER_UPDATE',
  VOTER_STATUS_DROPDOWN = 'VOTER_STATUS_DROPDOWN',
  VOTER_STATUS_VOTED = 'VOTER_STATUS_VOTED',
  VOTER_STATUS_REFUSED = 'VOTER_STATUS_REFUSED',
  VOTER_STATUS_SPAM = 'VOTER_STATUS_SPAM',
}
